cvconfiguration.example:
  path: '/cvconfiguration/example'
  defaults:
    _title: 'Example'
    _controller: '\Drupal\cvconfiguration\Controller\CvconfigurationController::build'
  requirements:
    _permission: 'access content'

cvconfiguration.settings_form:
  path: '/admin/config/system/cvconfiguration'
  defaults:
    _title: 'cvconfiguration settings'
    _form: 'Drupal\cvconfiguration\Form\SettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE
